const POPULATION_GROWTH = 1;
const POPULATION_PRODUCTION = 10;

const SQUAD_POPULATION_COST = 10;
const SQUAD_GOLD_COST = 300;
const SQUAD_SOLDIERS = 10;
const SQUAD_TRAINING_STEPS = 5;

export {
  POPULATION_GROWTH,
  POPULATION_PRODUCTION,
  SQUAD_GOLD_COST,
  SQUAD_POPULATION_COST,
  SQUAD_SOLDIERS,
  SQUAD_TRAINING_STEPS,
};
